# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yxuanf\Desktop\融合模型\main\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1066, 754)
        Form.setStyleSheet(
            "background-color: qlineargradient(x0:0, y1:0,x0:1, y2:1, stop:0 rgb(20, 32, 44), stop:1 rgb(37, 85, 117));\n"
            "border-radius:20px  "
        )
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(Form)
        self.Title.setStyleSheet(
            'font: 25pt "楷体";\n'
            "border:none;\n"
            "background-color: rgba(255, 255, 255, 0);\n"
            "color: rgb(255, 255, 255);\n"
            ""
        )
        self.Title.setObjectName("Title")
        self.horizontalLayout_3.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.NeuralButton = QtWidgets.QPushButton(Form)
        self.NeuralButton.setStyleSheet(
            "QPushButton{\n"
            "padding:8px;\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(226, 230, 255);\n"
            '    font: 12pt "楷体";\n'
            "    border-radius:16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(43, 162, 239);\n"
            "}\n"
            ""
        )
        self.NeuralButton.setObjectName("NeuralButton")
        self.verticalLayout.addWidget(self.NeuralButton)
        self.LoadmonitorData = QtWidgets.QPushButton(Form)
        self.LoadmonitorData.setStyleSheet(
            "QPushButton{\n"
            "padding:8px;\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(226, 230, 255);\n"
            '    font: 12pt "楷体";\n'
            "    border-radius:16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(43, 162, 239);\n"
            "}\n"
            ""
        )
        self.LoadmonitorData.setObjectName("LoadmonitorData")
        self.verticalLayout.addWidget(self.LoadmonitorData)
        self.ObserveData = QtWidgets.QPushButton(Form)
        self.ObserveData.setStyleSheet(
            "QPushButton{\n"
            "padding:8px;\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(226, 230, 255);\n"
            '    font: 12pt "楷体";\n'
            "    border-radius:16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(43, 162, 239);\n"
            "}\n"
            ""
        )
        self.ObserveData.setObjectName("ObserveData")
        self.verticalLayout.addWidget(self.ObserveData)
        self.clearEvidence = QtWidgets.QPushButton(Form)
        self.clearEvidence.setStyleSheet(
            "QPushButton{\n"
            "padding:8px;\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(226, 230, 255);\n"
            '    font: 12pt "楷体";\n'
            "    border-radius:16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(43, 162, 239);\n"
            "}\n"
            ""
        )
        self.clearEvidence.setObjectName("clearEvidence")
        self.verticalLayout.addWidget(self.clearEvidence)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.EvidenceBrowser = QtWidgets.QTextBrowser(Form)
        self.EvidenceBrowser.setStyleSheet(
            "color: rgb(0, 0, 0);\n"
            'font: 12pt "楷体";\n'
            "background-color:qlineargradient(spread:reflect, x1:0.0166818, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.931818 rgba(60, 88, 112, 255));\n"
            "border:0px solid red;\n"
            "border-radius:12px\n"
            "\n"
            ""
        )
        self.EvidenceBrowser.setObjectName("EvidenceBrowser")
        self.horizontalLayout.addWidget(self.EvidenceBrowser)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inferbutton = QtWidgets.QPushButton(Form)
        self.inferbutton.setStyleSheet(
            "QPushButton{\n"
            "padding:8px;\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(226, 230, 255);\n"
            '    font: 12pt "楷体";\n'
            "    border-radius:16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(0, 0, 0);\n"
            "    background-color: rgb(43, 162, 239);\n"
            "}\n"
            ""
        )
        self.inferbutton.setObjectName("inferbutton")
        self.horizontalLayout_2.addWidget(self.inferbutton)
        self.queryCombobox = QtWidgets.QComboBox(Form)
        self.queryCombobox.setStyleSheet(
            'font: 12pt "楷体";\n'
            "color: rgb(0, 0, 0);\n"
            "selection-color: rgb(255, 0, 0);\n"
            "background-color: rgb(255, 255, 255);"
        )
        self.queryCombobox.setObjectName("queryCombobox")
        self.horizontalLayout_2.addWidget(self.queryCombobox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(
            "QFrame{\n"
            "    background-color:qlineargradient(spread:reflect, x1:0.0166818, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.931818 rgba(60, 88, 112, 255));\n"
            "    border:0px solid red;\n"
            "    color: rgb(255, 254, 255);\n"
            "border-radius:12px\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 1)
        self.gridLayout_2.setRowMinimumHeight(1, 8)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 8)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "贝叶斯融合模型建模与推理"))
        self.NeuralButton.setText(_translate("Form", "神经网络融合"))
        self.LoadmonitorData.setText(_translate("Form", "导入监测数据"))
        self.ObserveData.setText(_translate("Form", "观测数据设置"))
        self.clearEvidence.setText(_translate("Form", "清除证据"))
        self.inferbutton.setText(_translate("Form", "融合推理"))
